services:
  # ---------------------------------------------------------
  # INFRASTRUCTURE TIER
  # ---------------------------------------------------------
  redis-cache:
    image: redis:7.2-alpine
    container_name: zkube-redis
    ports:
      - "6379:6379"
    networks:
      - zkube-network
    command: redis-server --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-db:
    image: postgres:16-alpine
    container_name: zkube-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: zkube_chaos
    ports:
      - "5434:5432"  
    networks:
      - zkube-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d zkube_chaos"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    container_name: zkube-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@zkube.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - zkube-network
    depends_on:
      postgres-db:
        condition: service_started

  # ---------------------------------------------------------
  # APPLICATION TIER
  # ---------------------------------------------------------
  accounts-service:
    image: zkube-accounts:latest
    container_name: zkube-accounts
    ports:
      - "8081:8081"
    networks:
      - zkube-network
    depends_on:
      postgres-db:
        condition: service_healthy

  transactions-service:
    image: zkube-transactions:latest
    container_name: zkube-transactions
    ports:
      - "8082:8082"
    networks:
      - zkube-network
    depends_on:
      postgres-db:
        condition: service_healthy
      redis-cache:
        condition: service_healthy

  notifications-service:
    image: zkube-notifications:latest
    container_name: zkube-notifications
    networks:
      - zkube-network
    depends_on:
      redis-cache:
        condition: service_healthy

# ---------------------------------------------------------
# NETWORKS & VOLUMES
# ---------------------------------------------------------
networks:
  zkube-network:
    driver: bridge

volumes:
  postgres-data: